[package]
name = "umpire"
version = "0.2.0"
authors = ["Josh Hansen <hansen.joshuaa@gmail.com>"]

[dependencies]
clap = "2.33.0"
cpal = "0.10.0"
csv = "1.1.1"
failure = "0.1.5"
flate2 = "1.0.11"
pastel = { path = "../External/pastel" }
#pastel = "0.5.2"
pitch_calc = "0.11.1"
sample = "0.10.0"
synth = "0.11.0" 
termion = "1.3.0"
rand = "0.7.0"
unicode-segmentation = "1.3.0"


