[package]
name = "umpire"
description = "Combat Quest of the Millennium"
version = "0.4.0"
authors = ["Josh Hansen <hansen.joshuaa@gmail.com>"]
license = "GPL-3.0-only"
categories = ["games"]
edition = "2018"
default-run = "umpire"
include = [
    "src/*",
    "README.md",
    "LICENSE",
    "doc/roadmap.md",
    "data/geonames_cities1000_2017-02-27_0201__pop-and-name.tsv.gz",
    "data/us-census/1990/givenname_rel_freqs.csv",
    "data/us-census/2010/surname_freqs.csv",
    "images/1945_Baseball_Umpire.txt",
]
repository = "https://github.com/joshhansen/Umpire"
homepage = "https://github.com/joshhansen/Umpire"

[badges]
travis-ci = { repository = "joshhansen/Umpire" }

[dependencies]
clap = "2.33.0"
cpal = "0.10.0"
crossterm = "0.16.0"
csv = "1.1.3"
failure = "0.1.6"
flate2 = "1.0.13"
pastel = "0.7.0"
pitch_calc = "0.11.1"
sample = "0.10.0"
synth = "0.11.0" 
rand = "0.7.3"
unicode-segmentation = "1.6.0"

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "explore"
harness = false
path = "benches/explore.rs"

[[bench]]
name = "grid"
harness = false
path = "benches/grid.rs"

[[bench]]
name = "nearest_adjacent_unobserved"
harness = false
path = "benches/nearest_adjacent_unobserved.rs"

[[bench]]
name = "wrapping"
harness = false
path = "benches/wrapping.rs"