[package]
name = "umpire"
version = "0.2.0"
authors = ["Josh Hansen <hansen.joshuaa@gmail.com>"]

[dependencies]
clap = "2.33.0"
csv = "1.1.1"
flate2 = "1.0.11"
pastel = { path = "../External/pastel" }
#sample = "0.6.2"
termion = "1.3.0"
rand = "0.7.0"
unicode-segmentation = "1.1.0"
