[package]
name = "umpire"
version = "0.2.0"
authors = ["Josh Hansen <hansen.joshuaa@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
cpal = "0.10.0"
crossterm = "0.10.2"
csv = "1.1.1"
failure = "0.1.5"
flate2 = "1.0.11"
pastel = { git = "https://github.com/rivy/rust.pastel.git", branch = "rf.distinct" }
pitch_calc = "0.11.1"
sample = "0.10.0"
synth = "0.11.0" 
rand = "0.7.0"
unicode-segmentation = "1.3.0"
