[package]
name = "umpire-ai"
version = "0.5.0-pre"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bincode = "1.2.1"
clap = { workspace = true }
common = { path = "../../common" }
crossterm = { workspace = true }
failure = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
tarpc = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

umpire-tui = { path = "../tui" }

# AI/ML
rsrl = { workspace = true }
tch = "0.1.7"
#tch = { path = "/home/josh/Projects/External/tch-rs" }

# BLAS for rsrl
blas-src = { workspace = true }
openblas-src = { workspace = true }